name: main
on:
  - push
  - pull_request

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nvim-versions:
          - 'stable'
          - 'nightly'
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install Plenary
        uses: actions/checkout@v2
        with:
          repository: nvim-lua/plenary.nvim
          path: ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim

      - name: Install Treesitter
        uses: actions/checkout@v2
        with:
          repository: nvim-treesitter/nvim-treesitter
          path: ~/.local/share/nvim/site/pack/vendor/start/nvim-treesitter.nvim

      - name: Install nui
        uses: actions/checkout@v2
        with:
          repository: MunifTanjim/nui.nvim
          path: ~/.local/share/nvim/site/pack/vendor/start/nui.nvim

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-versions }}

      - name: Test
        run: make ci

